server {
    listen 80;
    server_name altura-holdings.com www.altura-holdings.com;
    root /opt/atlasx-media/apps/altura-holdings;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/altura-holdings.access.log;
    error_log /var/log/nginx/altura-holdings.error.log;
}
